- hosts: localhost
  tasks:
    - name: build docker image
      local_action:
          module: docker_image
          path: docker_image
          name: neon-demo
          tag: v1
          state: build